// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: edge.proto

package workflow

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Edge is a Workflow edge connecting two nodes on the graph.
type Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Animated      *bool                  `protobuf:"varint,1,opt,name=animated,proto3,oneof" json:"animated,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Label         *string                `protobuf:"bytes,3,opt,name=label,proto3,oneof" json:"label,omitempty"`
	LabelStyle    *Edge_LabelStyle       `protobuf:"bytes,4,opt,name=label_style,json=labelStyle,proto3,oneof" json:"label_style,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	SourceHandle  *string                `protobuf:"bytes,6,opt,name=source_handle,json=sourceHandle,proto3,oneof" json:"source_handle,omitempty"`
	Style         *Edge_Style            `protobuf:"bytes,7,opt,name=style,proto3,oneof" json:"style,omitempty"`
	Target        string                 `protobuf:"bytes,8,opt,name=target,proto3" json:"target,omitempty"`
	TargetHandle  *string                `protobuf:"bytes,9,opt,name=target_handle,json=targetHandle,proto3,oneof" json:"target_handle,omitempty"`
	Type          string                 `protobuf:"bytes,10,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_edge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_edge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_edge_proto_rawDescGZIP(), []int{0}
}

func (x *Edge) GetAnimated() bool {
	if x != nil && x.Animated != nil {
		return *x.Animated
	}
	return false
}

func (x *Edge) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Edge) GetLabel() string {
	if x != nil && x.Label != nil {
		return *x.Label
	}
	return ""
}

func (x *Edge) GetLabelStyle() *Edge_LabelStyle {
	if x != nil {
		return x.LabelStyle
	}
	return nil
}

func (x *Edge) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Edge) GetSourceHandle() string {
	if x != nil && x.SourceHandle != nil {
		return *x.SourceHandle
	}
	return ""
}

func (x *Edge) GetStyle() *Edge_Style {
	if x != nil {
		return x.Style
	}
	return nil
}

func (x *Edge) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Edge) GetTargetHandle() string {
	if x != nil && x.TargetHandle != nil {
		return *x.TargetHandle
	}
	return ""
}

func (x *Edge) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Edges struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Edges         []*Edge                `protobuf:"bytes,1,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edges) Reset() {
	*x = Edges{}
	mi := &file_edge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edges) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edges) ProtoMessage() {}

func (x *Edges) ProtoReflect() protoreflect.Message {
	mi := &file_edge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edges.ProtoReflect.Descriptor instead.
func (*Edges) Descriptor() ([]byte, []int) {
	return file_edge_proto_rawDescGZIP(), []int{1}
}

func (x *Edges) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type Edge_LabelStyle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fill          string                 `protobuf:"bytes,1,opt,name=fill,proto3" json:"fill,omitempty"`
	FontWeight    string                 `protobuf:"bytes,2,opt,name=font_weight,json=fontWeight,proto3" json:"font_weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge_LabelStyle) Reset() {
	*x = Edge_LabelStyle{}
	mi := &file_edge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge_LabelStyle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge_LabelStyle) ProtoMessage() {}

func (x *Edge_LabelStyle) ProtoReflect() protoreflect.Message {
	mi := &file_edge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge_LabelStyle.ProtoReflect.Descriptor instead.
func (*Edge_LabelStyle) Descriptor() ([]byte, []int) {
	return file_edge_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Edge_LabelStyle) GetFill() string {
	if x != nil {
		return x.Fill
	}
	return ""
}

func (x *Edge_LabelStyle) GetFontWeight() string {
	if x != nil {
		return x.FontWeight
	}
	return ""
}

type Edge_Style struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stroke        string                 `protobuf:"bytes,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	StrokeWidth   int32                  `protobuf:"varint,2,opt,name=stroke_width,json=strokeWidth,proto3" json:"stroke_width,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge_Style) Reset() {
	*x = Edge_Style{}
	mi := &file_edge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge_Style) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge_Style) ProtoMessage() {}

func (x *Edge_Style) ProtoReflect() protoreflect.Message {
	mi := &file_edge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge_Style.ProtoReflect.Descriptor instead.
func (*Edge_Style) Descriptor() ([]byte, []int) {
	return file_edge_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Edge_Style) GetStroke() string {
	if x != nil {
		return x.Stroke
	}
	return ""
}

func (x *Edge_Style) GetStrokeWidth() int32 {
	if x != nil {
		return x.StrokeWidth
	}
	return 0
}

var File_edge_proto protoreflect.FileDescriptor

const file_edge_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"edge.proto\x12\x05proto\"\xb2\x04\n" +
	"\x04Edge\x12\x1f\n" +
	"\banimated\x18\x01 \x01(\bH\x00R\banimated\x88\x01\x01\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x19\n" +
	"\x05label\x18\x03 \x01(\tH\x01R\x05label\x88\x01\x01\x12<\n" +
	"\vlabel_style\x18\x04 \x01(\v2\x16.proto.Edge.LabelStyleH\x02R\n" +
	"labelStyle\x88\x01\x01\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12(\n" +
	"\rsource_handle\x18\x06 \x01(\tH\x03R\fsourceHandle\x88\x01\x01\x12,\n" +
	"\x05style\x18\a \x01(\v2\x11.proto.Edge.StyleH\x04R\x05style\x88\x01\x01\x12\x16\n" +
	"\x06target\x18\b \x01(\tR\x06target\x12(\n" +
	"\rtarget_handle\x18\t \x01(\tH\x05R\ftargetHandle\x88\x01\x01\x12\x12\n" +
	"\x04type\x18\n" +
	" \x01(\tR\x04type\x1aA\n" +
	"\n" +
	"LabelStyle\x12\x12\n" +
	"\x04fill\x18\x01 \x01(\tR\x04fill\x12\x1f\n" +
	"\vfont_weight\x18\x02 \x01(\tR\n" +
	"fontWeight\x1aB\n" +
	"\x05Style\x12\x16\n" +
	"\x06stroke\x18\x01 \x01(\tR\x06stroke\x12!\n" +
	"\fstroke_width\x18\x02 \x01(\x05R\vstrokeWidthB\v\n" +
	"\t_animatedB\b\n" +
	"\x06_labelB\x0e\n" +
	"\f_label_styleB\x10\n" +
	"\x0e_source_handleB\b\n" +
	"\x06_styleB\x10\n" +
	"\x0e_target_handle\"*\n" +
	"\x05Edges\x12!\n" +
	"\x05edges\x18\x01 \x03(\v2\v.proto.EdgeR\x05edgesB\vZ\t/workflowb\x06proto3"

var (
	file_edge_proto_rawDescOnce sync.Once
	file_edge_proto_rawDescData []byte
)

func file_edge_proto_rawDescGZIP() []byte {
	file_edge_proto_rawDescOnce.Do(func() {
		file_edge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_edge_proto_rawDesc), len(file_edge_proto_rawDesc)))
	})
	return file_edge_proto_rawDescData
}

var file_edge_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_edge_proto_goTypes = []any{
	(*Edge)(nil),            // 0: proto.Edge
	(*Edges)(nil),           // 1: proto.Edges
	(*Edge_LabelStyle)(nil), // 2: proto.Edge.LabelStyle
	(*Edge_Style)(nil),      // 3: proto.Edge.Style
}
var file_edge_proto_depIdxs = []int32{
	2, // 0: proto.Edge.label_style:type_name -> proto.Edge.LabelStyle
	3, // 1: proto.Edge.style:type_name -> proto.Edge.Style
	0, // 2: proto.Edges.edges:type_name -> proto.Edge
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_edge_proto_init() }
func file_edge_proto_init() {
	if File_edge_proto != nil {
		return
	}
	file_edge_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_edge_proto_rawDesc), len(file_edge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_edge_proto_goTypes,
		DependencyIndexes: file_edge_proto_depIdxs,
		MessageInfos:      file_edge_proto_msgTypes,
	}.Build()
	File_edge_proto = out.File
	file_edge_proto_goTypes = nil
	file_edge_proto_depIdxs = nil
}
