// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: get_workflow.proto

package workflow

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// WorkflowResponse is the response provided to the client containing the Workflow configuration (nodes and edges).
type WorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Edges         []*Edge                `protobuf:"bytes,1,rep,name=edges,proto3" json:"edges,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Nodes         []*Node                `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowResponse) Reset() {
	*x = WorkflowResponse{}
	mi := &file_get_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowResponse) ProtoMessage() {}

func (x *WorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_get_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowResponse.ProtoReflect.Descriptor instead.
func (*WorkflowResponse) Descriptor() ([]byte, []int) {
	return file_get_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *WorkflowResponse) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *WorkflowResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkflowResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_get_workflow_proto protoreflect.FileDescriptor

const file_get_workflow_proto_rawDesc = "" +
	"\n" +
	"\x12get_workflow.proto\x12\x05proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\n" +
	"node.proto\x1a\n" +
	"edge.proto\"h\n" +
	"\x10WorkflowResponse\x12!\n" +
	"\x05edges\x18\x01 \x03(\v2\v.proto.EdgeR\x05edges\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12!\n" +
	"\x05nodes\x18\x03 \x03(\v2\v.proto.NodeR\x05nodesB\vZ\t/workflowb\x06proto3"

var (
	file_get_workflow_proto_rawDescOnce sync.Once
	file_get_workflow_proto_rawDescData []byte
)

func file_get_workflow_proto_rawDescGZIP() []byte {
	file_get_workflow_proto_rawDescOnce.Do(func() {
		file_get_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_get_workflow_proto_rawDesc), len(file_get_workflow_proto_rawDesc)))
	})
	return file_get_workflow_proto_rawDescData
}

var file_get_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_get_workflow_proto_goTypes = []any{
	(*WorkflowResponse)(nil), // 0: proto.WorkflowResponse
	(*Edge)(nil),             // 1: proto.Edge
	(*Node)(nil),             // 2: proto.Node
}
var file_get_workflow_proto_depIdxs = []int32{
	1, // 0: proto.WorkflowResponse.edges:type_name -> proto.Edge
	2, // 1: proto.WorkflowResponse.nodes:type_name -> proto.Node
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_get_workflow_proto_init() }
func file_get_workflow_proto_init() {
	if File_get_workflow_proto != nil {
		return
	}
	file_node_proto_init()
	file_edge_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_get_workflow_proto_rawDesc), len(file_get_workflow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_get_workflow_proto_goTypes,
		DependencyIndexes: file_get_workflow_proto_depIdxs,
		MessageInfos:      file_get_workflow_proto_msgTypes,
	}.Build()
	File_get_workflow_proto = out.File
	file_get_workflow_proto_goTypes = nil
	file_get_workflow_proto_depIdxs = nil
}
