// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: integration_api_response.proto

package workflow

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IntegrationApiResponse struct {
	state                protoimpl.MessageState                      `protogen:"open.v1"`
	Latitude             float64                                     `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64                                     `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	GenerationTimeMs     float64                                     `protobuf:"fixed64,3,opt,name=generation_time_ms,json=generationtime_ms,proto3" json:"generation_time_ms,omitempty"`
	UtcOffsetSeconds     int64                                       `protobuf:"varint,4,opt,name=utc_offset_seconds,proto3" json:"utc_offset_seconds,omitempty"`
	Timezone             string                                      `protobuf:"bytes,5,opt,name=timezone,proto3" json:"timezone,omitempty"`
	TimezoneAbbreviation string                                      `protobuf:"bytes,6,opt,name=timezone_abbreviation,proto3" json:"timezone_abbreviation,omitempty"`
	Elevation            float64                                     `protobuf:"fixed64,7,opt,name=elevation,proto3" json:"elevation,omitempty"`
	CurrentWeatherUnits  *IntegrationApiResponse_CurrentWeatherUnits `protobuf:"bytes,8,opt,name=current_weather_units,proto3" json:"current_weather_units,omitempty"`
	CurrentWeather       *IntegrationApiResponse_CurrentWeather      `protobuf:"bytes,9,opt,name=current_weather,proto3" json:"current_weather,omitempty"`
	Error                *bool                                       `protobuf:"varint,10,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Reason               *string                                     `protobuf:"bytes,11,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *IntegrationApiResponse) Reset() {
	*x = IntegrationApiResponse{}
	mi := &file_integration_api_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrationApiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrationApiResponse) ProtoMessage() {}

func (x *IntegrationApiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_integration_api_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrationApiResponse.ProtoReflect.Descriptor instead.
func (*IntegrationApiResponse) Descriptor() ([]byte, []int) {
	return file_integration_api_response_proto_rawDescGZIP(), []int{0}
}

func (x *IntegrationApiResponse) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *IntegrationApiResponse) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *IntegrationApiResponse) GetGenerationTimeMs() float64 {
	if x != nil {
		return x.GenerationTimeMs
	}
	return 0
}

func (x *IntegrationApiResponse) GetUtcOffsetSeconds() int64 {
	if x != nil {
		return x.UtcOffsetSeconds
	}
	return 0
}

func (x *IntegrationApiResponse) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *IntegrationApiResponse) GetTimezoneAbbreviation() string {
	if x != nil {
		return x.TimezoneAbbreviation
	}
	return ""
}

func (x *IntegrationApiResponse) GetElevation() float64 {
	if x != nil {
		return x.Elevation
	}
	return 0
}

func (x *IntegrationApiResponse) GetCurrentWeatherUnits() *IntegrationApiResponse_CurrentWeatherUnits {
	if x != nil {
		return x.CurrentWeatherUnits
	}
	return nil
}

func (x *IntegrationApiResponse) GetCurrentWeather() *IntegrationApiResponse_CurrentWeather {
	if x != nil {
		return x.CurrentWeather
	}
	return nil
}

func (x *IntegrationApiResponse) GetError() bool {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return false
}

func (x *IntegrationApiResponse) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

type IntegrationApiResponse_CurrentWeatherUnits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          string                 `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Interval      string                 `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`
	Temperature   string                 `protobuf:"bytes,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	WindSpeed     string                 `protobuf:"bytes,4,opt,name=wind_speed,json=windspeed,proto3" json:"wind_speed,omitempty"`
	WindDirection string                 `protobuf:"bytes,5,opt,name=wind_direction,json=winddirection,proto3" json:"wind_direction,omitempty"`
	IsDay         string                 `protobuf:"bytes,6,opt,name=is_day,json=isday,proto3" json:"is_day,omitempty"`
	WeatherCode   string                 `protobuf:"bytes,7,opt,name=weather_code,json=weathercode,proto3" json:"weather_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegrationApiResponse_CurrentWeatherUnits) Reset() {
	*x = IntegrationApiResponse_CurrentWeatherUnits{}
	mi := &file_integration_api_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrationApiResponse_CurrentWeatherUnits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrationApiResponse_CurrentWeatherUnits) ProtoMessage() {}

func (x *IntegrationApiResponse_CurrentWeatherUnits) ProtoReflect() protoreflect.Message {
	mi := &file_integration_api_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrationApiResponse_CurrentWeatherUnits.ProtoReflect.Descriptor instead.
func (*IntegrationApiResponse_CurrentWeatherUnits) Descriptor() ([]byte, []int) {
	return file_integration_api_response_proto_rawDescGZIP(), []int{0, 0}
}

func (x *IntegrationApiResponse_CurrentWeatherUnits) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *IntegrationApiResponse_CurrentWeatherUnits) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *IntegrationApiResponse_CurrentWeatherUnits) GetTemperature() string {
	if x != nil {
		return x.Temperature
	}
	return ""
}

func (x *IntegrationApiResponse_CurrentWeatherUnits) GetWindSpeed() string {
	if x != nil {
		return x.WindSpeed
	}
	return ""
}

func (x *IntegrationApiResponse_CurrentWeatherUnits) GetWindDirection() string {
	if x != nil {
		return x.WindDirection
	}
	return ""
}

func (x *IntegrationApiResponse_CurrentWeatherUnits) GetIsDay() string {
	if x != nil {
		return x.IsDay
	}
	return ""
}

func (x *IntegrationApiResponse_CurrentWeatherUnits) GetWeatherCode() string {
	if x != nil {
		return x.WeatherCode
	}
	return ""
}

type IntegrationApiResponse_CurrentWeather struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          string                 `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Interval      int64                  `protobuf:"varint,2,opt,name=interval,proto3" json:"interval,omitempty"`
	Temperature   float64                `protobuf:"fixed64,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	WindSpeed     float64                `protobuf:"fixed64,4,opt,name=wind_speed,json=windspeed,proto3" json:"wind_speed,omitempty"`
	WindDirection float64                `protobuf:"fixed64,5,opt,name=wind_direction,json=winddirection,proto3" json:"wind_direction,omitempty"`
	IsDay         int64                  `protobuf:"varint,6,opt,name=is_day,proto3" json:"is_day,omitempty"`
	WeatherCode   int64                  `protobuf:"varint,7,opt,name=weather_code,json=weathercode,proto3" json:"weather_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegrationApiResponse_CurrentWeather) Reset() {
	*x = IntegrationApiResponse_CurrentWeather{}
	mi := &file_integration_api_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrationApiResponse_CurrentWeather) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrationApiResponse_CurrentWeather) ProtoMessage() {}

func (x *IntegrationApiResponse_CurrentWeather) ProtoReflect() protoreflect.Message {
	mi := &file_integration_api_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrationApiResponse_CurrentWeather.ProtoReflect.Descriptor instead.
func (*IntegrationApiResponse_CurrentWeather) Descriptor() ([]byte, []int) {
	return file_integration_api_response_proto_rawDescGZIP(), []int{0, 1}
}

func (x *IntegrationApiResponse_CurrentWeather) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *IntegrationApiResponse_CurrentWeather) GetInterval() int64 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *IntegrationApiResponse_CurrentWeather) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *IntegrationApiResponse_CurrentWeather) GetWindSpeed() float64 {
	if x != nil {
		return x.WindSpeed
	}
	return 0
}

func (x *IntegrationApiResponse_CurrentWeather) GetWindDirection() float64 {
	if x != nil {
		return x.WindDirection
	}
	return 0
}

func (x *IntegrationApiResponse_CurrentWeather) GetIsDay() int64 {
	if x != nil {
		return x.IsDay
	}
	return 0
}

func (x *IntegrationApiResponse_CurrentWeather) GetWeatherCode() int64 {
	if x != nil {
		return x.WeatherCode
	}
	return 0
}

var File_integration_api_response_proto protoreflect.FileDescriptor

const file_integration_api_response_proto_rawDesc = "" +
	"\n" +
	"\x1eintegration_api_response.proto\x12\x05proto\"\xff\a\n" +
	"\x16IntegrationApiResponse\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12-\n" +
	"\x12generation_time_ms\x18\x03 \x01(\x01R\x11generationtime_ms\x12.\n" +
	"\x12utc_offset_seconds\x18\x04 \x01(\x03R\x12utc_offset_seconds\x12\x1a\n" +
	"\btimezone\x18\x05 \x01(\tR\btimezone\x124\n" +
	"\x15timezone_abbreviation\x18\x06 \x01(\tR\x15timezone_abbreviation\x12\x1c\n" +
	"\televation\x18\a \x01(\x01R\televation\x12g\n" +
	"\x15current_weather_units\x18\b \x01(\v21.proto.IntegrationApiResponse.CurrentWeatherUnitsR\x15current_weather_units\x12V\n" +
	"\x0fcurrent_weather\x18\t \x01(\v2,.proto.IntegrationApiResponse.CurrentWeatherR\x0fcurrent_weather\x12\x19\n" +
	"\x05error\x18\n" +
	" \x01(\bH\x00R\x05error\x88\x01\x01\x12\x1b\n" +
	"\x06reason\x18\v \x01(\tH\x01R\x06reason\x88\x01\x01\x1a\xe7\x01\n" +
	"\x13CurrentWeatherUnits\x12\x12\n" +
	"\x04time\x18\x01 \x01(\tR\x04time\x12\x1a\n" +
	"\binterval\x18\x02 \x01(\tR\binterval\x12 \n" +
	"\vtemperature\x18\x03 \x01(\tR\vtemperature\x12\x1d\n" +
	"\n" +
	"wind_speed\x18\x04 \x01(\tR\twindspeed\x12%\n" +
	"\x0ewind_direction\x18\x05 \x01(\tR\rwinddirection\x12\x15\n" +
	"\x06is_day\x18\x06 \x01(\tR\x05isday\x12!\n" +
	"\fweather_code\x18\a \x01(\tR\vweathercode\x1a\xe3\x01\n" +
	"\x0eCurrentWeather\x12\x12\n" +
	"\x04time\x18\x01 \x01(\tR\x04time\x12\x1a\n" +
	"\binterval\x18\x02 \x01(\x03R\binterval\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x01R\vtemperature\x12\x1d\n" +
	"\n" +
	"wind_speed\x18\x04 \x01(\x01R\twindspeed\x12%\n" +
	"\x0ewind_direction\x18\x05 \x01(\x01R\rwinddirection\x12\x16\n" +
	"\x06is_day\x18\x06 \x01(\x03R\x06is_day\x12!\n" +
	"\fweather_code\x18\a \x01(\x03R\vweathercodeB\b\n" +
	"\x06_errorB\t\n" +
	"\a_reasonB\vZ\t/workflowb\x06proto3"

var (
	file_integration_api_response_proto_rawDescOnce sync.Once
	file_integration_api_response_proto_rawDescData []byte
)

func file_integration_api_response_proto_rawDescGZIP() []byte {
	file_integration_api_response_proto_rawDescOnce.Do(func() {
		file_integration_api_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_integration_api_response_proto_rawDesc), len(file_integration_api_response_proto_rawDesc)))
	})
	return file_integration_api_response_proto_rawDescData
}

var file_integration_api_response_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_integration_api_response_proto_goTypes = []any{
	(*IntegrationApiResponse)(nil),                     // 0: proto.IntegrationApiResponse
	(*IntegrationApiResponse_CurrentWeatherUnits)(nil), // 1: proto.IntegrationApiResponse.CurrentWeatherUnits
	(*IntegrationApiResponse_CurrentWeather)(nil),      // 2: proto.IntegrationApiResponse.CurrentWeather
}
var file_integration_api_response_proto_depIdxs = []int32{
	1, // 0: proto.IntegrationApiResponse.current_weather_units:type_name -> proto.IntegrationApiResponse.CurrentWeatherUnits
	2, // 1: proto.IntegrationApiResponse.current_weather:type_name -> proto.IntegrationApiResponse.CurrentWeather
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_integration_api_response_proto_init() }
func file_integration_api_response_proto_init() {
	if File_integration_api_response_proto != nil {
		return
	}
	file_integration_api_response_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_integration_api_response_proto_rawDesc), len(file_integration_api_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_integration_api_response_proto_goTypes,
		DependencyIndexes: file_integration_api_response_proto_depIdxs,
		MessageInfos:      file_integration_api_response_proto_msgTypes,
	}.Build()
	File_integration_api_response_proto = out.File
	file_integration_api_response_proto_goTypes = nil
	file_integration_api_response_proto_depIdxs = nil
}
