// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: node.proto

package workflow

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Metadata represents the information provided for configuration of a specific node.
type MetaData struct {
	state               protoimpl.MessageState  `protogen:"open.v1"`
	ApiEndpoint         *string                 `protobuf:"bytes,1,opt,name=api_endpoint,json=apiEndpoint,proto3,oneof" json:"api_endpoint,omitempty"`
	ConditionExpression *string                 `protobuf:"bytes,2,opt,name=condition_expression,json=conditionExpression,proto3,oneof" json:"condition_expression,omitempty"`
	EmailTemplate       *MetaData_EmailTemplate `protobuf:"bytes,3,opt,name=email_template,json=emailTemplate,proto3,oneof" json:"email_template,omitempty"`
	HasHandles          *MetaData_HasHandles    `protobuf:"bytes,4,opt,name=has_handles,json=hasHandles,proto3" json:"has_handles,omitempty"`
	InputFields         []string                `protobuf:"bytes,5,rep,name=input_fields,json=inputFields,proto3" json:"input_fields,omitempty"`
	InputVariables      []string                `protobuf:"bytes,6,rep,name=input_variables,json=inputVariables,proto3" json:"input_variables,omitempty"`
	Options             []*MetaData_Option      `protobuf:"bytes,7,rep,name=options,proto3" json:"options,omitempty"`
	OutputVariables     []string                `protobuf:"bytes,8,rep,name=output_variables,json=outputVariables,proto3" json:"output_variables,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MetaData) Reset() {
	*x = MetaData{}
	mi := &file_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaData) ProtoMessage() {}

func (x *MetaData) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaData.ProtoReflect.Descriptor instead.
func (*MetaData) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0}
}

func (x *MetaData) GetApiEndpoint() string {
	if x != nil && x.ApiEndpoint != nil {
		return *x.ApiEndpoint
	}
	return ""
}

func (x *MetaData) GetConditionExpression() string {
	if x != nil && x.ConditionExpression != nil {
		return *x.ConditionExpression
	}
	return ""
}

func (x *MetaData) GetEmailTemplate() *MetaData_EmailTemplate {
	if x != nil {
		return x.EmailTemplate
	}
	return nil
}

func (x *MetaData) GetHasHandles() *MetaData_HasHandles {
	if x != nil {
		return x.HasHandles
	}
	return nil
}

func (x *MetaData) GetInputFields() []string {
	if x != nil {
		return x.InputFields
	}
	return nil
}

func (x *MetaData) GetInputVariables() []string {
	if x != nil {
		return x.InputVariables
	}
	return nil
}

func (x *MetaData) GetOptions() []*MetaData_Option {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *MetaData) GetOutputVariables() []string {
	if x != nil {
		return x.OutputVariables
	}
	return nil
}

// *
// Node is a node within the Workflow which represents a task or action executed.
type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Node_Data             `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Position      *Node_Position         `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1}
}

func (x *Node) GetData() *Node_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetPosition() *Node_Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Node) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Nodes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nodes) Reset() {
	*x = Nodes{}
	mi := &file_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nodes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nodes) ProtoMessage() {}

func (x *Nodes) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nodes.ProtoReflect.Descriptor instead.
func (*Nodes) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{2}
}

func (x *Nodes) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type MetaData_EmailTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          string                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaData_EmailTemplate) Reset() {
	*x = MetaData_EmailTemplate{}
	mi := &file_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaData_EmailTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaData_EmailTemplate) ProtoMessage() {}

func (x *MetaData_EmailTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaData_EmailTemplate.ProtoReflect.Descriptor instead.
func (*MetaData_EmailTemplate) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MetaData_EmailTemplate) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *MetaData_EmailTemplate) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

type MetaData_HasHandles struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        *structpb.Value        `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target        *structpb.Value        `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaData_HasHandles) Reset() {
	*x = MetaData_HasHandles{}
	mi := &file_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaData_HasHandles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaData_HasHandles) ProtoMessage() {}

func (x *MetaData_HasHandles) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaData_HasHandles.ProtoReflect.Descriptor instead.
func (*MetaData_HasHandles) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0, 1}
}

func (x *MetaData_HasHandles) GetSource() *structpb.Value {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *MetaData_HasHandles) GetTarget() *structpb.Value {
	if x != nil {
		return x.Target
	}
	return nil
}

type MetaData_Option struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Lat           float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,3,opt,name=lon,proto3" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaData_Option) Reset() {
	*x = MetaData_Option{}
	mi := &file_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaData_Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaData_Option) ProtoMessage() {}

func (x *MetaData_Option) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaData_Option.ProtoReflect.Descriptor instead.
func (*MetaData_Option) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0, 2}
}

func (x *MetaData_Option) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *MetaData_Option) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *MetaData_Option) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type Node_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Metadata      *MetaData              `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Type          *string                `protobuf:"bytes,4,opt,name=type,proto3,oneof" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node_Data) Reset() {
	*x = Node_Data{}
	mi := &file_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node_Data) ProtoMessage() {}

func (x *Node_Data) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node_Data.ProtoReflect.Descriptor instead.
func (*Node_Data) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Node_Data) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Node_Data) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Node_Data) GetMetadata() *MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Node_Data) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

type Node_Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node_Position) Reset() {
	*x = Node_Position{}
	mi := &file_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node_Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node_Position) ProtoMessage() {}

func (x *Node_Position) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node_Position.ProtoReflect.Descriptor instead.
func (*Node_Position) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Node_Position) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Node_Position) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_node_proto protoreflect.FileDescriptor

const file_node_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"node.proto\x12\x05proto\x1a\x1cgoogle/protobuf/struct.proto\"\xc7\x05\n" +
	"\bMetaData\x12&\n" +
	"\fapi_endpoint\x18\x01 \x01(\tH\x00R\vapiEndpoint\x88\x01\x01\x126\n" +
	"\x14condition_expression\x18\x02 \x01(\tH\x01R\x13conditionExpression\x88\x01\x01\x12I\n" +
	"\x0eemail_template\x18\x03 \x01(\v2\x1d.proto.MetaData.EmailTemplateH\x02R\remailTemplate\x88\x01\x01\x12;\n" +
	"\vhas_handles\x18\x04 \x01(\v2\x1a.proto.MetaData.HasHandlesR\n" +
	"hasHandles\x12!\n" +
	"\finput_fields\x18\x05 \x03(\tR\vinputFields\x12'\n" +
	"\x0finput_variables\x18\x06 \x03(\tR\x0einputVariables\x120\n" +
	"\aoptions\x18\a \x03(\v2\x16.proto.MetaData.OptionR\aoptions\x12)\n" +
	"\x10output_variables\x18\b \x03(\tR\x0foutputVariables\x1a=\n" +
	"\rEmailTemplate\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x1al\n" +
	"\n" +
	"HasHandles\x12.\n" +
	"\x06source\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\x06source\x12.\n" +
	"\x06target\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x06target\x1a@\n" +
	"\x06Option\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x03 \x01(\x01R\x03lonB\x0f\n" +
	"\r_api_endpointB\x17\n" +
	"\x15_condition_expressionB\x11\n" +
	"\x0f_email_template\"\xba\x02\n" +
	"\x04Node\x12$\n" +
	"\x04data\x18\x01 \x01(\v2\x10.proto.Node.DataR\x04data\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x120\n" +
	"\bposition\x18\x03 \x01(\v2\x14.proto.Node.PositionR\bposition\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x1a\x8d\x01\n" +
	"\x04Data\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12+\n" +
	"\bmetadata\x18\x03 \x01(\v2\x0f.proto.MetaDataR\bmetadata\x12\x17\n" +
	"\x04type\x18\x04 \x01(\tH\x00R\x04type\x88\x01\x01B\a\n" +
	"\x05_type\x1a&\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"*\n" +
	"\x05Nodes\x12!\n" +
	"\x05nodes\x18\x01 \x03(\v2\v.proto.NodeR\x05nodesB\vZ\t/workflowb\x06proto3"

var (
	file_node_proto_rawDescOnce sync.Once
	file_node_proto_rawDescData []byte
)

func file_node_proto_rawDescGZIP() []byte {
	file_node_proto_rawDescOnce.Do(func() {
		file_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)))
	})
	return file_node_proto_rawDescData
}

var file_node_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_node_proto_goTypes = []any{
	(*MetaData)(nil),               // 0: proto.MetaData
	(*Node)(nil),                   // 1: proto.Node
	(*Nodes)(nil),                  // 2: proto.Nodes
	(*MetaData_EmailTemplate)(nil), // 3: proto.MetaData.EmailTemplate
	(*MetaData_HasHandles)(nil),    // 4: proto.MetaData.HasHandles
	(*MetaData_Option)(nil),        // 5: proto.MetaData.Option
	(*Node_Data)(nil),              // 6: proto.Node.Data
	(*Node_Position)(nil),          // 7: proto.Node.Position
	(*structpb.Value)(nil),         // 8: google.protobuf.Value
}
var file_node_proto_depIdxs = []int32{
	3, // 0: proto.MetaData.email_template:type_name -> proto.MetaData.EmailTemplate
	4, // 1: proto.MetaData.has_handles:type_name -> proto.MetaData.HasHandles
	5, // 2: proto.MetaData.options:type_name -> proto.MetaData.Option
	6, // 3: proto.Node.data:type_name -> proto.Node.Data
	7, // 4: proto.Node.position:type_name -> proto.Node.Position
	1, // 5: proto.Nodes.nodes:type_name -> proto.Node
	8, // 6: proto.MetaData.HasHandles.source:type_name -> google.protobuf.Value
	8, // 7: proto.MetaData.HasHandles.target:type_name -> google.protobuf.Value
	0, // 8: proto.Node.Data.metadata:type_name -> proto.MetaData
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_node_proto_init() }
func file_node_proto_init() {
	if File_node_proto != nil {
		return
	}
	file_node_proto_msgTypes[0].OneofWrappers = []any{}
	file_node_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_proto_goTypes,
		DependencyIndexes: file_node_proto_depIdxs,
		MessageInfos:      file_node_proto_msgTypes,
	}.Build()
	File_node_proto = out.File
	file_node_proto_goTypes = nil
	file_node_proto_depIdxs = nil
}
